### PR TITLE
Android auto flash firmware

### PR DESCRIPTION
**Pull request by superfrink**
Updated the Android USB driver to detect when a Labrador is connected in bootloader mode and return that state up to the generic USB driver which will flash the firmware.    Added latest firmware image to the Android package.

The logcat output when this event occurs looks like:
```
03-28 19:11:47.257  4553  4572 D Qt      : findDevice
03-28 19:11:47.301  4553  4572 D Qt      : DEVICE FOUND
03-28 19:11:47.334  4553  4572 D Qt      : Device ID = 1002
03-28 19:11:47.334  4553  4572 D Qt      : VID=0x03eb
03-28 19:11:47.334  4553  4572 D Qt      : PID=0x2fe4
03-28 19:11:47.339  4553  4572 D Qt      : Device found but it is in bootloader mode!
...
03-28 19:11:47.340  4553  4572 D Labrador: FLASHING FIRMWARE....
...
03-28 19:11:47.340  4553  4572 D Labrador: FLASHING  assets:/firmware/labrafirm_0006_02.hex
...
03-28 19:11:49.887  4553  4572 D Labrador: flashRet: 0
...
03-28 19:11:50.315  4553  4572 D Qt      : findDevice
03-28 19:11:50.322  4553  4572 D Qt      : NO DEVICE FOUND
...
03-28 19:11:50.731  4553  4572 D Qt      : findDevice
03-28 19:11:50.741  4553  4572 D Qt      : DEVICE FOUND
03-28 19:11:50.752  4553  4572 D Qt      : Device ID = 1004
03-28 19:11:50.752  4553  4572 D Qt      : VID=0x03eb
03-28 19:11:50.752  4553  4572 D Qt      : PID=0xba94
```

### CODE REVIEW

**Comment by superfrink** [comment]
Oh I see what happened there.  I'll see about resolving the conflict.

**Comment by EspoTek** [comment]
Code looks good, but any reason the .hex files have changed?

**Comment by superfrink** [comment]
The first time I ran the code it failed because the .hex file for version 6 variant 2 was not included in the Android package.  It worked after copying all of the .hex files from Desktop_Interface/bin/firmware/ to the Android assets directory included in the package.

I figured the Android app will not flash firmware for Windows 64 or versions before 6 so I took those out of the assets directory.

We could look at updating the build process to read the appropriate .hex file from Desktop_Interface/bin/firmware/ and include it in the Android package.

**Comment by EspoTek** [comment]
Apologies for the two week delay.  This is the first opportunity I've had in a while to look at code!

I've merged in your changes; everything makes sense!

**Pull request merged**
