### PR TITLE
Add .clang-format file

### PR DESCRIPTION
**Pull request by SebastianMestre**
Sorry about double PR. I got confused and messed up my branches.

### CODE REVIEW

**Comment by EspoTek** [comment]
All good man.  Looking good.  Let us know when you think it's ready to merge.  It's something I'd be interested to mess around with.  :)

**Comment by SebastianMestre** [comment]
Oops. Sorry to leave you hanging. I think it'd be fine you merged it now since it covers the main points. We'll figure out what else to add to it later on.

Also, I can't say I disagree with running this over all code in a single go.

**Comment by SebastianMestre** [comment]
Hey man, just letting you know, I feel like this should be good for now. We can add more rules to it when the need arises.

**Comment by EspoTek** [comment]
Bah!  Thought I'd already merged this weeks ago.  Sorry, man!

**Pull request merged**
